platform :ios, '8.0'
inhibit_all_warnings!

use_frameworks!

target 'HHDemo' do
    pod 'Masonry'
    pod 'ReactiveCocoa', '2.5'
    pod 'pop', '~> 1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'ASProgressPopUpView'
    pod 'SDWebImage', '~>3.8'
    pod 'AFNetworking', '~> 3.0'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'Aspects'
    pod 'PromiseKit', '~> 1.6'
    pod 'GPUImage'
    pod 'YYKit'
    pod 'AsyncDisplayKit'
    pod 'GDPerformanceView'
    pod 'KMCGeigerCounter'
    pod 'MLeaksFinder'
    pod 'YTKNetwork'
end
