platform :ios, '8.0'
inhibit_all_warnings!

use_frameworks!

target 'HHDemo' do
    pod 'Masonry'
    pod 'ReactiveCocoa', '2.5'
    pod 'pop', '~> 1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'ASProgressPopUpView'
    pod 'SDWebImage', '~>3.8'
end
